; PC98PLAYER.INI (â∫ãâê∂)
[PC98PLAYER]
Title=â∫ãâê∂
Start=KAKYU.BAT
Args=
Scale=2
FullScreen=0
Smooth=0
CpuMHz=16
Drive=A
SoundBoard=86
SoundIRQ=12
Volume=100
FMVolume=100
SSGVolume=100
BeepVolume=50
MouseSpeed=100
Font=ÇlÇr ÉSÉVÉbÉN
ExitOnEnd=1
PauseInactive=0
